doc.type.html
script
filename=covidstrings31background.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
div id=header/div
audio=new audio (audio_file mp3)
audio.play
random button
new button (set random color)
option button
new button (change color)
public fun with graphics(){
color panel=new  panel();
add (panel,center )
button panel
new panel (new flowlayout(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e){
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
colorm=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings31()
f.set title(covid strings31)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>0</label>
score=0
if (mult == x*y)
[non-concatenated]
score+=10
else:
score-=10
if (mult == x*y)
[concatenated]
score+=20
else:
score-=20
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:1,b:2,c:3,d:4,e:5,f:6,g:7,h:8}
keys object keys(team)
entries object entries(obj);
value object= [team color]
return filename
