doc.type html
script
filename=covidstrings31.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
div id=header/div
audio=new audio(audio_file mp3)
audio.play
random button
new button (set random color)
option button
new button (change color)
public fun with graphics(){
color panel=new panel();
add (panel,center )
button panel
new  panel(new flowlayout(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener){
override 
public actionperformed(actionevent e){
random r=newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionPerformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.ad(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe f=new covid strings31()
f.set title(covid strings31)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if(mult ==x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lbl score)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:1,b:2,c:3,d:4,e:5,f:6,g:7,h:8}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covid strings list31=[white transit angels,violet relivers,green peacemakers,magenta magnetizers,pink covid disease fighters,yellow moxie,burgundy rebuilders,red protein spikers]
covid strings phrase list31=[ non-concatenated strings "if one scientist believes covid started in a wuhan wet market then others might start believing too"
"according to science.com december2019 is a likely date for the first known sequence"
"research even suggests covid spread in a couple states before it was officially reported"
"even though mrna vaccines were successful containing covid early on researchers still want better options long-term"
"laurie garrets the coming plague is one sign that a pandemic will happen in the near future"
"spillover is yet another example of this future in more vivid detail"
"all this seems to point to the end of days even without the nostradamus predictions"
"if nostradamus predicted covid then the next nostradamus can predict the next pandemic"
concatenated strings
"covid"+"indeed"+"was"+"a"+"classic"+"example"+"of"+"the"+"storm"+"before"+"the"+"calm"
"the"+"covid"+"storm"+"was"+"different"+"from"+"the"+"great"+"frost"+"of"+"1709"
"it"+"was"+"also"+"different"+"from"+"nationwide"+"snowstorms"+"in"+"2022"
"the"+"one"+"difference"+"involved"+"politicians"+"being"+"unable"+"to"+"handle"+"it"
"the"+"historical"+"significance"+"of"+"this"+"will"+"be"+"that"+"americas"+"house"+"covid"+"speaking"+"was"+"on"+"fire"
"in"+"some"+"ways"+"it"+"is"+"up"+"to"+"us"+"to"+"shape"+"the"+"post"+"covid"+"world"
"for"+"example"+"four"+"years"+"later"+"we"+"now"+"know"+"that"+"long"+"covid"+"is"+"caused"+"by"+"leaky"+"blood"+"vessels"
"another"+"cause"+"involves"+"joint"+"hypermobility"]
covid strings31 multiple choice list=[1:a science b match c cool math games d the weather channel,2:a connectivity b hypermobility c tears d popping,3:a bleak b americas c greenlands d icelands,4:a bubonic plague b pandemic c weather ballon shortage d cough syrup shortage,5:a pre b post c before d into,6:a us dominance on the world stage b days c long-term planning d stock trading for congressmen,7:a 2022 b 2023 c 1977 d 1989,8:a questionably b officially c even d spirit halloween,9:a storm b equilibrium c twister d calm before the storm,10:a options b supply c selectiveness d damage control,11:a8 b13 c4 d5,12:a dystopia b past c future d present,13:a people b politicians c ai d social security,14:a detroit b wuhan c south park d european,15:a previous b current c next d last,16:a rsv b covid c norovirus d hantavirus] 
covid strings31 math problems list=[ non-concatenated "if a line shows the effect of spillover based on urbanization in america what would the relationship of the line be if the line increases"?,"if the line had a slope of5 and a y intercept of 2.2 what would the x coordinate be if the y coordinate was23"?,"if the previous covid point of(4.2,23) was reflected across the x axis what is the new point"?,"if the previous point was rotated 270 degrees counterclockwise what would the new point be"?,"if the previous point was rotated180 degrees what is the new point"?,"if the previous point was translated5 units down and0 units to the left what is the new point"?,"if the previous point was translated 4.2 units left and 6 units up what is the new point"?,"if the previous point was translated25 units right and16 units down what is the new point"?,
concatenated "if"+"67"+"percent"+"of"+"americans"+"say"+"covid"+"was"+"just"+"as"+"disprutive"+"as"+"nation-wide"+"snow-storms"+"in"+"2022"+"what"+"percent"+"dont"?,"if"+"18"+"percent"+"strongly"+"believe"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"2.022"+"percent"+"what"+"is"+"the"+"range"?,"if"+"73"+"percent"+"of"+"american"+"scientists"+"say"+"the"+"wet"+"market"+"played"+"some"+"sort"+"of"+"role"+"in"+"covid"+"spread"+"what"+"percent"+"dont"?,"if"+"30"+"percent"+"strongly"+"agree"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"4.43"+"percent"+"what"+"is"+"the"+"range"?]
covid strings31 scrambled phrase list=["ovicd"+"oobk"+"spillover","ovicd"+"oobk"+"coming"+"plague"]
covid strings31bonusquestion=("a future edition of the coming plague will be called the covid coming plague")
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
import syntax
chart js 
def gradient
id=mygradient
gradient units=userspaceonuse
if function slope>=1:
return direct relationship
else:
return  inverse or no relationship
x1=0
y1=2.2
x2=23
y2=x2*5+y1
stop offset=0 stop-color ff0000
stop offset=1 stop color=0000ff
linear gradient
filter
id=linear1
filter units=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fe component transfer>
<fe func covid strings  type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection==x axis:
shift x axis
else:
remain
if rotation==270 degrees counterclockwise:
shift 270 degrees counterclockwise
else:
remain
if rotation==180 degrees:
shift 180 degrees
else:
remain
if translation==(0,-5):
shift 5 units down
else:
remain
if translation==(-4.2,6)
shift 4.2 units left and 6 units up
else:
remain
if translation ==(25,-16)
shift 25 units right and 16 units down 
substring(start,end)
userin.multiple choice
if (s1.length())!=s2.length: 
return false
if s1.length()==s2.length:
return true
char[]arr1=s1.tochararray
char[]arr2=s2.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings31 
console log users team wins covid strings31 
else:
return game over
return filename
